@startuml AdminPanelSequenceDiagram

header "Верхний уровень декомпозиции"
footer "Просто какой-то подвал, йоу"
title "Функциональность админ-панели"

actor "Пользователь ТГ" as user
participant "Телеграм-бот" as bot
participant "Приложение" as app
database "RouletteDB" as db

user -> bot++ : Переходит в главное меню
bot --> app++ : Переход в главное меню
app --> db++ : SELECT-запрос к таблице USER
db -->> app-- : Отправка данных о пользователе
app --> app : User.TgId == OWNER_TG_ID ?
alt #Pink Пользователь ТГ НЕ Администратор
    app -->> bot : Ответ без раздела "Админ-панель"
    bot -->> user : Ответ без раздела "Админ-панель"
    ... Обычная работа программы ...
else #LightBlue Пользователь ТГ — Администратор
    app -->> bot-- : Ответ с разделом "Админ-панель"
    bot -->> user-- : Ответ с разделом "Админ-панель"
    == Переход в раздел "Админ-панель" ==
        user -> bot++ : Переход в раздел "Админ-панель"
        bot --> app++ : Переход в состояние "AdminPanelState"
        app --> db++ : UPDATE-запрос к таблице USER
        db --> db : Изменение BotStateId у User
        db -->> app-- : Ответ об изменении данных
        app -->> bot-- : Сообщение с функциями админа
        bot -->> user-- : Сообщение с функциями админа
    == Функциональность "Админ-панели" ==
        opt #LightYellow Функция "Начисление очков игроку"
            group #White Переход в раздел начисления очков игроку
                user -> bot++ : Переход в раздел "Начисление баллов игроку"
                bot --> app++ : Переход в состояние "AdminPanel_ChangePlayerPoints"
                app --> db++ : UPDATE-запрос к таблице USER
                db --> db : Изменение BotStateId у User
                db -->> app-- : Ответ об изменении состояния
                app -->> bot-- : Сообщение при переходе в раздел функции
                bot -->> user-- : Сообщение при переходе в раздел функции
            end
            group #White Начисление очков игроку
                user -> bot++ : Вводит служебное сообщение
                note right : TEMPLATE : "User_TgId Score",
                bot --> app++ : Отправляет служебное сообщение
                app --> app : Проверка сообщения на формат ввода
                alt #LightPink Некорректный ввод
                    app -->> bot : Сообщение о некорректном вводе
                    bot -->> user : Сообщение о некорректном вводе
                else #LightBlue Корректный ввод
                    app --> db++ : UPDATE-запрос к таблице USER
                    db --> db : Изменение Score (и MaxScore) у User
                    db -->> app-- : Ответ об успешном начислении
                    app -->> bot-- : Ответ об успешном начислении
                    bot -->> user-- : Ответ об успешном начислении
                end 
            end
        end
        opt #LightYellow Функция "Вернуться"
            user -> bot++ : Переход в раздел "[Вернуться]"
            bot --> app++ : Переход в состояние "ToWaitingState"
            app --> db++ : UPDATE-запрос к таблице USER
            db --> db : Изменение BotStateId у User
            db -->> app-- : Ответ об изменении состояния
            app -->> bot-- : Сообщение при переходе в раздел
            bot -->> user-- : Сообщение при переходе в раздел
        end
end

@enduml