@startuml AdminPanelSequenceDiagram

header "Верхний уровень декомпозиции"
footer "Просто какой-то подвал, йоу"
title "Функциональность админ-панели"

actor "Пользователь ТГ" as p
participant "Телеграм-бот" as bot
participant "Приложение" as app
database "RouletteDB" as db

p -> bot++ : Переходит в главное меню
bot --> app++ : Переход в главное меню
app --> db++ : SELECT-запрос к таблице USER
db -->> app-- : Отправка данных о пользователе
' app --> app : Telegram ID = OWNER_TG_ID ?
alt #Pink Пользователь ТГ НЕ Администратор
    app -->> bot : Ответ без раздела "Админ-панель"
    bot -->> p : Ответ без раздела "Админ-панель"
else #LightBlue Пользователь ТГ — Администратор
    app -->> bot-- : Ответ с разделом "Админ-панель"
    bot -->> p-- : Ответ с разделом "Админ-панель"
    == Переход в раздел "Админ-панель" ==
        p -> bot++ : Переход в раздел "Админ-панель"
        bot --> app++ : Переход в состояние "AdminPanelState"
        app --> db++ : UPDATE-запрос к таблице USER
        db --> db : Изменение BotStateId у User
        db -->> app-- : Ответ об изменении данных
        app -->> bot-- : Ответ при переходе в это состояние
        bot -->> p-- : Ответ при переходе в это состояние
    == Функциональность "Админ-панели" ==
        opt #LightYellow Функция "Начисление баллов игроку"

        end
        opt #LightGreen Функция "Вернуться"

        end
end

@enduml